// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ParamField 声明规则的一个参数，供前端自动生成表单、服务端校验。
 */
export interface ParamField {
    "name": string;
    "label": string;

    /**
     * int | float | string | bool | ref
     */
    "type": string;

    /**
     * Type == ref 时的目标实体类型
     */
    "refKind"?: string;
    "default"?: any;
}
