// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Capability 求解器能力声明：认哪些硬约束原语、哪些代价原语，是否承诺全局最优。
 */
export interface Capability {
    "constraints": string[] | null;
    "costs": string[] | null;
    "optimal": boolean;
}
