// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CalendarService 管理日历、排班日与值班约束。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetCalendar 取该排班的日历配置，没有则返回 nil。
 */
export function GetCalendar(scopeID: number): $CancellablePromise<$models.CalendarConfig | null> {
    return $Call.ByID(2416847148, scopeID);
}

/**
 * ListDuties 列出该排班全部值班约束。
 */
export function ListDuties(scopeID: number): $CancellablePromise<$models.DutyView[] | null> {
    return $Call.ByID(815674286, scopeID);
}

/**
 * ListScheduleDays 列出该排班全部要排的日期。
 */
export function ListScheduleDays(scopeID: number): $CancellablePromise<string[] | null> {
    return $Call.ByID(1998094664, scopeID);
}

/**
 * SaveCalendar 保存日历并按日期与星期重算排班日。
 * 首次保存时会插入两条全局公平规则（fair_count、fair_interval）。
 */
export function SaveCalendar(scopeID: number, cfg: $models.CalendarConfig): $CancellablePromise<void> {
    return $Call.ByID(2885136313, scopeID, cfg);
}

/**
 * SetDuty 设置某天某班次某老师的值班状态：required 值班、off 不值班、unspecified 取消指定。
 */
export function SetDuty(scopeID: number, day: string, shiftID: number, teacherID: number, status: string): $CancellablePromise<void> {
    return $Call.ByID(2644736314, scopeID, day, shiftID, teacherID, status);
}

/**
 * ToggleScheduleDay 把某天加入或排除排班日历，返回操作后是否在排班日内。
 * 排除时同时软删当天的值班；取消排除时把这一天加回排班日。
 */
export function ToggleScheduleDay(scopeID: number, day: string): $CancellablePromise<boolean> {
    return $Call.ByID(3901876095, scopeID, day);
}
