// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetadataService 管理范围内的实体：老师、班级、学科、学科标签、班次，以及任课绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BindByText 按「课程 班级 老师」的文本批量建立任课绑定。
 * 每行一条，空白分隔三列，顺序固定为 课程 / 班级 / 老师；三者在当前排班里都必须已存在。
 * 只要有一行不合法（列数不对、实体不存在、同名无法确定）整批就不写入，逐行原因放进 errors；
 * 这样一次粘贴要么全部成功、要么不改动任何数据，用户改完重贴即可。
 * 已经存在的绑定不算错误，跳过并计入 skipped。
 */
export function BindByText(scopeID: number, text: string): $CancellablePromise<$models.BindTextResult> {
    return $Call.ByID(2170603944, scopeID, text);
}

/**
 * ClearTeacherBindings 清除若干老师名下的全部任课绑定，老师本身保留。
 * 老师不存在或本来就没有绑定都直接跳过，不报错；整体在一个事务里完成。
 */
export function ClearTeacherBindings(scopeID: number, teacherIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(2507035858, scopeID, teacherIDs);
}

/**
 * DeleteDataset 软删实体：老师 / 班级 / 学科连带删相关任课，并连带软删引用它的值班与课表格子；删标签只解除挂载，内置标签不允许删除。
 */
export function DeleteDataset(scopeID: number, id: number): $CancellablePromise<void> {
    return $Call.ByID(3984673282, scopeID, id);
}

/**
 * DeleteDatasets 批量软删实体，已经不存在（或被删过）的直接跳过。老师 / 班级 / 学科 / 班次 / 学科标签都走这里。
 */
export function DeleteDatasets(scopeID: number, ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(1401434083, scopeID, ids);
}

/**
 * ListDatasets 列出某类型的实体；老师与班级会带上任课，供列表展示。
 */
export function ListDatasets(scopeID: number, typ: string, keyword: string): $CancellablePromise<$models.DatasetView[] | null> {
    return $Call.ByID(2089247028, scopeID, typ, keyword);
}

/**
 * ListSubjectTags 列出范围内全部学科标签，并统计各标签被多少学科挂载。
 */
export function ListSubjectTags(scopeID: number): $CancellablePromise<$models.TagView[] | null> {
    return $Call.ByID(69382358, scopeID);
}

/**
 * SaveDataset 新增或改名。id 为 0 表示新增。
 */
export function SaveDataset(scopeID: number, typ: string, id: number, name: string): $CancellablePromise<$models.DatasetView> {
    return $Call.ByID(2229424056, scopeID, typ, id, name);
}

/**
 * SaveDatasets 批量添加实体：先对入参去重（粘贴的文本本身可能重复），
 * 再和库里已有的名称对比，重复的不写入。支持老师、班级、学科、学科标签，班次还要填时间段。
 */
export function SaveDatasets(scopeID: number, typ: string, names: string[] | null): $CancellablePromise<$models.BatchResult> {
    return $Call.ByID(4215512209, scopeID, typ, names);
}

/**
 * SaveMergedClass 新增或修改合班，整表替换成员物理班。id 为 0 表示新增。
 * 合班名在 merged_class 内唯一；成员只能是物理班且至少 2 个；同一物理班可属于多个合班。
 */
export function SaveMergedClass(scopeID: number, id: number, name: string, memberIDs: number[] | null): $CancellablePromise<$models.DatasetView> {
    return $Call.ByID(1879245264, scopeID, id, name, memberIDs);
}

/**
 * SaveShift 新增或修改班次，时间段不能与已有班次重叠。区间按左闭右开比较。
 */
export function SaveShift(scopeID: number, id: number, name: string, start: string, end: string): $CancellablePromise<$models.DatasetView> {
    return $Call.ByID(3980491572, scopeID, id, name, start, end);
}

/**
 * SaveSubjectTags 整表替换一个学科的标签挂载。
 */
export function SaveSubjectTags(scopeID: number, subjectID: number, tagIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(3183403265, scopeID, subjectID, tagIDs);
}

/**
 * SaveTeacherBindings 整表替换一个老师的任课关系。
 */
export function SaveTeacherBindings(scopeID: number, teacherID: number, pairs: $models.BindingInput[] | null): $CancellablePromise<void> {
    return $Call.ByID(3750727264, scopeID, teacherID, pairs);
}
