// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetadataService 管理范围内的实体：老师、班级、学科、班次，以及任课绑定。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteDataset 软删实体：老师 / 班级 / 学科连带删相关任课，并连带软删引用它的值班与课表格子。
 */
export function DeleteDataset(scopeID: number, id: number): $CancellablePromise<void> {
    return $Call.ByID(3984673282, scopeID, id);
}

/**
 * DeleteDatasets 批量软删实体，已经不存在（或被删过）的直接跳过。老师 / 班级 / 学科 / 班次都走这里。
 */
export function DeleteDatasets(scopeID: number, ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(1401434083, scopeID, ids);
}

/**
 * ListDatasets 列出某类型的实体；老师与班级会带上任课，供列表展示。
 */
export function ListDatasets(scopeID: number, typ: string, keyword: string): $CancellablePromise<$models.DatasetView[] | null> {
    return $Call.ByID(2089247028, scopeID, typ, keyword);
}

/**
 * SaveDataset 新增或改名。id 为 0 表示新增。
 */
export function SaveDataset(scopeID: number, typ: string, id: number, name: string): $CancellablePromise<$models.DatasetView> {
    return $Call.ByID(2229424056, scopeID, typ, id, name);
}

/**
 * SaveDatasets 批量添加实体：先对入参去重（粘贴的文本本身可能重复），
 * 再和库里已有的名称对比，重复的不写入。只支持老师、班级、学科，班次还要填时间段。
 */
export function SaveDatasets(scopeID: number, typ: string, names: string[] | null): $CancellablePromise<$models.BatchResult> {
    return $Call.ByID(4215512209, scopeID, typ, names);
}

/**
 * SaveShift 新增或修改班次，时间段不能与已有班次重叠。区间按左闭右开比较。
 */
export function SaveShift(scopeID: number, id: number, name: string, start: string, end: string): $CancellablePromise<$models.DatasetView> {
    return $Call.ByID(3980491572, scopeID, id, name, start, end);
}

/**
 * SaveTeacherBindings 整表替换一个老师的任课关系。
 */
export function SaveTeacherBindings(scopeID: number, teacherID: number, pairs: $models.BindingInput[] | null): $CancellablePromise<void> {
    return $Call.ByID(3750727264, scopeID, teacherID, pairs);
}
