// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BatchResult 批量添加的结果。
 */
export interface BatchResult {
    "inserted": string[] | null;
    "duplicates": string[] | null;
}

/**
 * BindingInput 任课绑定的输入项。
 */
export interface BindingInput {
    "subjectId": number;
    "classId": number;
}

/**
 * BindingView 一条任课关系：老师 + 学科 + 班级。一条任课在库里是三条 mapping。
 */
export interface BindingView {
    "teacherId": number;
    "teacher": string;
    "subjectId": number;
    "subject": string;
    "classId": number;
    "class": string;
}

/**
 * CalendarConfig 日历配置：起止日期 + 哪些星期上课。
 */
export interface CalendarConfig {
    "startDate": string;
    "endDate": string;
    "weekdays": boolean[] | null;
    "solver": string;
}

/**
 * DatasetView 元数据实体；老师与班级附带任课信息，班次附带起止时间。
 */
export interface DatasetView {
    "id": number;
    "name": string;
    "start": string;
    "end": string;
    "bindings": BindingView[] | null;
}

/**
 * DutyView 一条值班约束：某天某班次某老师必须值班或必须休息。
 */
export interface DutyView {
    "day": string;
    "shiftId": number;
    "shift": string;
    "teacherId": number;
    "teacher": string;
    "required": boolean;
}

/**
 * ScopeInfo 排班范围（一个排班）。
 */
export interface ScopeInfo {
    "id": number;
    "name": string;
}
