// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BatchResult 批量添加的结果。
 */
export interface BatchResult {
    "inserted": string[] | null;
    "duplicates": string[] | null;
}

/**
 * BindTextResult 文本批量绑定的结果。errors 非空表示整批都没有写入。
 */
export interface BindTextResult {
    "inserted": number;
    "skipped": number;
    "errors": string[] | null;
}

/**
 * BindingInput 任课绑定的输入项。
 */
export interface BindingInput {
    "subjectId": number;
    "classId": number;
}

/**
 * BindingView 一条任课关系：老师 + 学科 + 班级。一条任课在库里是三条 mapping。
 */
export interface BindingView {
    "teacherId": number;
    "teacher": string;
    "subjectId": number;
    "subject": string;
    "classId": number;
    "class": string;
}

/**
 * CalendarConfig 日历配置：起止日期 + 哪些星期上课。
 */
export interface CalendarConfig {
    "startDate": string;
    "endDate": string;
    "weekdays": boolean[] | null;
    "solver": string;
}

/**
 * DatasetView 元数据实体；老师与班级附带任课信息，班次附带起止时间，学科附带标签，合班附带成员。
 */
export interface DatasetView {
    "id": number;
    "name": string;
    "start": string;
    "end": string;
    "bindings": BindingView[] | null;
    "tagIds": number[] | null;
    "members": MemberView[] | null;
}

/**
 * DutyView 一条值班约束：某天某班次某老师必须值班或必须休息。
 */
export interface DutyView {
    "day": string;
    "shiftId": number;
    "shift": string;
    "teacherId": number;
    "teacher": string;
    "required": boolean;
}

/**
 * MemberView 合班包含的一个物理班。
 */
export interface MemberView {
    "id": number;
    "name": string;
}

/**
 * ScopeInfo 排班范围（一个排班）。
 */
export interface ScopeInfo {
    "id": number;
    "name": string;
}

/**
 * TagView 一个学科标签、被多少学科挂载，以及是否为内置标签（内置的不允许删除）。
 */
export interface TagView {
    "id": number;
    "name": string;
    "count": number;
    "builtin": boolean;
}
