// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScheduleService 暴露排班核心能力：规则元信息、结果读写、结果复核。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as plan$0 from "../plan/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check 对当前结果做一次复核，返回冲突清单。只读，不重排。
 */
export function Check(scopeID: number): $CancellablePromise<plan$0.Violation[] | null> {
    return $Call.ByID(4102037547, scopeID);
}

/**
 * ClearAssignment 软删一个格子。
 */
export function ClearAssignment(scopeID: number, day: string, shiftID: number, classID: number): $CancellablePromise<void> {
    return $Call.ByID(3852099451, scopeID, day, shiftID, classID);
}

/**
 * ListAssignments 列出课表格子。versionID 为 0 表示当前结果，否则是某版本快照。
 */
export function ListAssignments(scopeID: number, versionID: number): $CancellablePromise<$models.AssignmentView[] | null> {
    return $Call.ByID(1210976345, scopeID, versionID);
}

/**
 * RuleTypes 列出所有已注册的规则类型（按 type 排序，保证顺序稳定）。
 */
export function RuleTypes(): $CancellablePromise<$models.RuleView[] | null> {
    return $Call.ByID(2165385468);
}

/**
 * SetAssignment 写入/更新一个格子。teacherID 为 0 表示清空该格（保留行）。
 * locked 为真时求解器不得改动它。
 */
export function SetAssignment(scopeID: number, day: string, shiftID: number, classID: number, teacherID: number, locked: boolean): $CancellablePromise<void> {
    return $Call.ByID(3091810022, scopeID, day, shiftID, classID, teacherID, locked);
}
