// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScopeService 管理排班范围：切换的前提是有一个排班列表。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateScope 新建排班，名称不能与现有排班重复。
 */
export function CreateScope(name: string): $CancellablePromise<$models.ScopeInfo> {
    return $Call.ByID(2178267934, name);
}

/**
 * DeleteScope 逻辑删除一个排班，它下面的全部数据一起软删。
 */
export function DeleteScope(scopeID: number): $CancellablePromise<void> {
    return $Call.ByID(2307052903, scopeID);
}

/**
 * ListScopes 返回未删除的排班，按创建顺序。
 */
export function ListScopes(): $CancellablePromise<$models.ScopeInfo[] | null> {
    return $Call.ByID(1550398247);
}

/**
 * PurgeDeleted 把全库里逻辑删除的数据做物理删除，返回删除的行数。
 * 表按「子表在前」的顺序清理，避免外键 RESTRICT 拦住父表。
 */
export function PurgeDeleted(): $CancellablePromise<number> {
    return $Call.ByID(1770497606);
}

/**
 * RenameScope 修改排班名称。
 */
export function RenameScope(scopeID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2679365260, scopeID, name);
}
