// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Level 冲突级别。
 */
export enum Level {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LevelHard = "hard",
    LevelSoft = "soft",
    LevelInfo = "info",
};

export type TeacherID = number;

/**
 * UnitID / TeacherID 在契约内部用独立类型，避免与数据库 id、班次 id 混用。
 */
export type UnitID = number;

/**
 * Violation 检查器报出的一条冲突。
 */
export interface Violation {
    "level": Level;
    "kind": string;
    "unit"?: UnitID | null;
    "teacher"?: TeacherID | null;
    "ruleLabel"?: string;
    "message": string;
    "delta"?: number;
}
